export const SECTION_BACKGROUNDS = [
   {value: 'image-bg', name: 'Image Background'},
   {value: 'color-bg', name: 'Color Background'},
];

export const SECTION_BG_OVERLAYS = [
   {value: 'bg-overlay', name: 'Default'},
   {value: 'bg-overlay-gray', name: 'Gray'},
   {value: 'bg-overlay-primary', name: 'Primary'},
   {value: 'bg-overlay-primary-light', name: 'Primary Light'},
   {value: 'bg-overlay-secondary', name: 'Secondary'},
   {value: 'bg-overlay-secondary-light', name: 'Secondary Light'},
   {value: 'bg-overlay-gradient', name: 'Gradient'},
   {value: 'bg-overlay-gradient-light', name: 'Gradient Light'},
];

export const HERO_SECTION_DESIGNS = [
   {value: 'hero-aligned-left', name: 'Text Aligned Left', description: 'Simple hero section with the details aligned to the left'},
   {value: 'hero-with-carousel', name: 'Hero With Carousel', description: 'A hero section a sliding carousel'},
   {value: 'hero-with-carousel-aligned-left', name: 'Hero With Carousel Text Aligned Left', description: 'A hero section a sliding carousel and its details are aligned to the left.'},
];

export const CARD_ICONS = [
   {value: 'mdi-lightbulb-on-outline', name: 'Lightbulb On'},
   {value: 'mdi-bullseye', name: 'Bullseye'},
   {value: 'mdi-bullseye-arrow', name: 'Bullseye Arrow'},
   {value: 'mdi-diamond-stone', name: 'Diamond Stone'},
   {value: 'mdi-handshake', name: 'Handshake Icon'},
   {value: 'mdi-shield-check', name: 'Shield Check Icon'},
   {value: 'mdi-trophy-award', name: 'Trophy Award Icon'},
   {value: 'mdi-seal', name: 'Seal Icon'},
   {value: 'mdi-earth', name: 'Earth Icon'},
   {value: 'mdi-account-heart', name: 'Heart'},
   {value: 'mdi-clock-check', name: 'Clock Check'},
   {value: 'mdi-hard-hat', name: 'Hat'},
   {value: 'mdi-leaf', name: 'Leaf'},
   {value: 'mdi-speedometer', name: 'Speedometer Icon'},
   {value: 'mdi-account-group', name: 'Account Group Icon'},
   {value: 'mdi-tree', name: 'Tree Icon'},
   {value: 'mdi-chart-line', name: 'Chart Line Icon'},
   {value: 'mdi-home-outline', name: 'Home'},
   {value: 'mdi-map-marker', name: 'Location'},
   {value: 'mdi-parking', name: 'Parking'},
   {value: 'mdi-elevator', name: 'Elevator'},
   {value: 'mdi-wifi', name: 'Wi-Fi'},
   {value: 'mdi-security', name: 'Security'},
   {value: 'mdi-fire-extinguisher', name: 'Fire Extinguisher'},
   {value: 'mdi-shield-check', name: 'Security Check'},
   {value: 'mdi-lightbulb-on-outline', name: 'Lighting'},
   {value: 'mdi-access-point', name: 'Internet Access Point'},
   {value: 'mdi-cctv', name: 'CCTV'},
   {value: 'mdi-water', name: 'Water Supply'},
   {value: 'mdi-flash', name: 'Electricity'},
   {value: 'mdi-silverware-fork-knife', name: 'Cutlery'},
   {value: 'mdi-food', name: 'Food'},
   {value: 'mdi-food-fork-drink', name: 'Food & Drink'},
   {value: 'mdi-coffee', name: 'Coffee'},
   {value: 'mdi-bottle-wine', name: 'Wine'},
   {value: 'mdi-fridge', name: 'Refrigerator'},
   {value: 'mdi-stove', name: 'Kitchen'},
   {value: 'mdi-microwave', name: 'Microwave'},
   {value: 'mdi-pot-steam-outline', name: 'Cooking Area'},
   {value: 'mdi-fire', name: 'Grill'},
   {value: 'mdi-water-outline', name: 'Drinking Water'},
   {value: 'mdi-table-furniture', name: 'Table'},
   {value: 'mdi-chair-school', name: 'Chair'},
   {value: 'mdi-sofa-outline', name: 'Sofa'},
   {value: 'mdi-lamp-outline', name: 'Table Lamp'},
   {value: 'mdi-cup', name: 'Cup Service'},
   {value: 'mdi-bottle-wine-outline', name: 'Wine Service'},
   {value: 'mdi-plate-cutlery', name: 'Dining Table'},
   {value: 'mdi-nature-people', name: 'Outdoor Table'},
   {value: 'mdi-umbrella-beach', name: 'Patio Area'},
   {value: 'mdi-tree', name: 'Garden'},
   {value: 'mdi-pool', name: 'Swimming Pool'},
   {value: 'mdi-basketball-hoop-outline', name: 'Basketball Court'},
   {value: 'mdi-dumbbell', name: 'Gym'},
   {value: 'mdi-bicycle', name: 'Cycling Area'},
   {value: 'mdi-campfire', name: 'Campfire Area'},
   {value: 'mdi-palm-tree', name: 'Resort Area'},
   {value: 'mdi-tennis', name: 'Tennis Court'},
   {value: 'mdi-beach', name: 'Beach Access'},
   {value: 'mdi-briefcase-outline', name: 'Work Area'},
   {value: 'mdi-printer', name: 'Printer'},
   {value: 'mdi-laptop', name: 'Laptop Friendly'},
   {value: 'mdi-account-multiple', name: 'Meeting Room'},
   {value: 'mdi-phone', name: 'Telephone'},
   {value: 'mdi-clock-outline', name: '24h Service'},
   {value: 'mdi-truck-delivery', name: 'Delivery'},
   {value: 'mdi-trophy-outline', name: 'Award'},
];

export const CTA_BUTTON_TYPES = [
   {value: 'btn-primary', name: 'Primary Button'},
   {value: 'btn-secondary', name: 'Secondary Button'},
   {value: 'btn-default', name: 'Default Button'},
];
